name: inline-source

on: push

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18', '20']
    name: Install, build, and test (Node ${{ matrix.node }})

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Cache pnpm modules'
        uses: actions/cache@v3
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 'Install pnpm 8'
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.x

      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: 'Set up npm credentials'
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Configure pnpm'
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: 'Install dependencies'
        run: pnpm --frozen-lockfile install

      - name: 'Build'
        run: pnpm run clean && pnpm run build

      - name: 'Test'
        run: pnpm test
