name: inline-source

on: push

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  build_deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18', '20']
    name: Install, build, and test (Node ${{ matrix.node }})

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.x

      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm --frozen-lockfile install

      - name: 'Build'
        run: pnpm run build

      - name: 'Test'
        run: pnpm run test
